################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../moses/src/AlignmentInfo.cpp \
../moses/src/AlignmentInfoCollection.cpp \
../moses/src/BilingualDynSuffixArray.cpp \
../moses/src/BitmapContainer.cpp \
../moses/src/ChartCell.cpp \
../moses/src/ChartCellCollection.cpp \
../moses/src/ChartHypothesis.cpp \
../moses/src/ChartHypothesisCollection.cpp \
../moses/src/ChartManager.cpp \
../moses/src/ChartTranslationOption.cpp \
../moses/src/ChartTranslationOptionCollection.cpp \
../moses/src/ChartTranslationOptionList.cpp \
../moses/src/ChartTrellisDetour.cpp \
../moses/src/ChartTrellisDetourQueue.cpp \
../moses/src/ChartTrellisNode.cpp \
../moses/src/ChartTrellisPath.cpp \
../moses/src/ConfusionNet.cpp \
../moses/src/DecodeFeature.cpp \
../moses/src/DecodeGraph.cpp \
../moses/src/DecodeStep.cpp \
../moses/src/DecodeStepGeneration.cpp \
../moses/src/DecodeStepTranslation.cpp \
../moses/src/Dictionary.cpp \
../moses/src/DummyScoreProducers.cpp \
../moses/src/DynSuffixArray.cpp \
../moses/src/FFState.cpp \
../moses/src/Factor.cpp \
../moses/src/FactorCollection.cpp \
../moses/src/FactorTypeSet.cpp \
../moses/src/FeatureFunction.cpp \
../moses/src/File.cpp \
../moses/src/FloydWarshall.cpp \
../moses/src/GenerationDictionary.cpp \
../moses/src/GlobalLexicalModel.cpp \
../moses/src/Hypothesis.cpp \
../moses/src/HypothesisStack.cpp \
../moses/src/HypothesisStackCubePruning.cpp \
../moses/src/HypothesisStackNormal.cpp \
../moses/src/InputFileStream.cpp \
../moses/src/InputType.cpp \
../moses/src/LMList.cpp \
../moses/src/LVoc.cpp \
../moses/src/LexicalReordering.cpp \
../moses/src/LexicalReorderingState.cpp \
../moses/src/LexicalReorderingTable.cpp \
../moses/src/Manager.cpp \
../moses/src/NonTerminal.cpp \
../moses/src/PCNTools.cpp \
../moses/src/Parameter.cpp \
../moses/src/PartialTranslOptColl.cpp \
../moses/src/Phrase.cpp \
../moses/src/PhraseDictionary.cpp \
../moses/src/PhraseDictionaryDynSuffixArray.cpp \
../moses/src/PhraseDictionaryMemory.cpp \
../moses/src/PhraseDictionaryNode.cpp \
../moses/src/PhraseDictionaryTree.cpp \
../moses/src/PhraseDictionaryTreeAdaptor.cpp \
../moses/src/PrefixTreeMap.cpp \
../moses/src/ReorderingConstraint.cpp \
../moses/src/ReorderingStack.cpp \
../moses/src/RuleCube.cpp \
../moses/src/RuleCubeItem.cpp \
../moses/src/RuleCubeQueue.cpp \
../moses/src/ScoreComponentCollection.cpp \
../moses/src/ScoreIndexManager.cpp \
../moses/src/ScoreProducer.cpp \
../moses/src/Search.cpp \
../moses/src/SearchCubePruning.cpp \
../moses/src/SearchNormal.cpp \
../moses/src/Sentence.cpp \
../moses/src/SentenceStats.cpp \
../moses/src/SquareMatrix.cpp \
../moses/src/StaticData.cpp \
../moses/src/SyntacticLanguageModel.cpp \
../moses/src/TargetPhrase.cpp \
../moses/src/TargetPhraseCollection.cpp \
../moses/src/ThreadPool.cpp \
../moses/src/Timer.cpp \
../moses/src/TranslationOption.cpp \
../moses/src/TranslationOptionCollection.cpp \
../moses/src/TranslationOptionCollectionConfusionNet.cpp \
../moses/src/TranslationOptionCollectionText.cpp \
../moses/src/TranslationOptionList.cpp \
../moses/src/TranslationSystem.cpp \
../moses/src/TreeInput.cpp \
../moses/src/TrellisPath.cpp \
../moses/src/TrellisPathCollection.cpp \
../moses/src/UserMessage.cpp \
../moses/src/Util.cpp \
../moses/src/Word.cpp \
../moses/src/WordLattice.cpp \
../moses/src/WordsBitmap.cpp \
../moses/src/WordsRange.cpp \
../moses/src/XmlOption.cpp \
../moses/src/hash.cpp 

OBJS += \
./moses/src/AlignmentInfo.o \
./moses/src/AlignmentInfoCollection.o \
./moses/src/BilingualDynSuffixArray.o \
./moses/src/BitmapContainer.o \
./moses/src/ChartCell.o \
./moses/src/ChartCellCollection.o \
./moses/src/ChartHypothesis.o \
./moses/src/ChartHypothesisCollection.o \
./moses/src/ChartManager.o \
./moses/src/ChartTranslationOption.o \
./moses/src/ChartTranslationOptionCollection.o \
./moses/src/ChartTranslationOptionList.o \
./moses/src/ChartTrellisDetour.o \
./moses/src/ChartTrellisDetourQueue.o \
./moses/src/ChartTrellisNode.o \
./moses/src/ChartTrellisPath.o \
./moses/src/ConfusionNet.o \
./moses/src/DecodeFeature.o \
./moses/src/DecodeGraph.o \
./moses/src/DecodeStep.o \
./moses/src/DecodeStepGeneration.o \
./moses/src/DecodeStepTranslation.o \
./moses/src/Dictionary.o \
./moses/src/DummyScoreProducers.o \
./moses/src/DynSuffixArray.o \
./moses/src/FFState.o \
./moses/src/Factor.o \
./moses/src/FactorCollection.o \
./moses/src/FactorTypeSet.o \
./moses/src/FeatureFunction.o \
./moses/src/File.o \
./moses/src/FloydWarshall.o \
./moses/src/GenerationDictionary.o \
./moses/src/GlobalLexicalModel.o \
./moses/src/Hypothesis.o \
./moses/src/HypothesisStack.o \
./moses/src/HypothesisStackCubePruning.o \
./moses/src/HypothesisStackNormal.o \
./moses/src/InputFileStream.o \
./moses/src/InputType.o \
./moses/src/LMList.o \
./moses/src/LVoc.o \
./moses/src/LexicalReordering.o \
./moses/src/LexicalReorderingState.o \
./moses/src/LexicalReorderingTable.o \
./moses/src/Manager.o \
./moses/src/NonTerminal.o \
./moses/src/PCNTools.o \
./moses/src/Parameter.o \
./moses/src/PartialTranslOptColl.o \
./moses/src/Phrase.o \
./moses/src/PhraseDictionary.o \
./moses/src/PhraseDictionaryDynSuffixArray.o \
./moses/src/PhraseDictionaryMemory.o \
./moses/src/PhraseDictionaryNode.o \
./moses/src/PhraseDictionaryTree.o \
./moses/src/PhraseDictionaryTreeAdaptor.o \
./moses/src/PrefixTreeMap.o \
./moses/src/ReorderingConstraint.o \
./moses/src/ReorderingStack.o \
./moses/src/RuleCube.o \
./moses/src/RuleCubeItem.o \
./moses/src/RuleCubeQueue.o \
./moses/src/ScoreComponentCollection.o \
./moses/src/ScoreIndexManager.o \
./moses/src/ScoreProducer.o \
./moses/src/Search.o \
./moses/src/SearchCubePruning.o \
./moses/src/SearchNormal.o \
./moses/src/Sentence.o \
./moses/src/SentenceStats.o \
./moses/src/SquareMatrix.o \
./moses/src/StaticData.o \
./moses/src/SyntacticLanguageModel.o \
./moses/src/TargetPhrase.o \
./moses/src/TargetPhraseCollection.o \
./moses/src/ThreadPool.o \
./moses/src/Timer.o \
./moses/src/TranslationOption.o \
./moses/src/TranslationOptionCollection.o \
./moses/src/TranslationOptionCollectionConfusionNet.o \
./moses/src/TranslationOptionCollectionText.o \
./moses/src/TranslationOptionList.o \
./moses/src/TranslationSystem.o \
./moses/src/TreeInput.o \
./moses/src/TrellisPath.o \
./moses/src/TrellisPathCollection.o \
./moses/src/UserMessage.o \
./moses/src/Util.o \
./moses/src/Word.o \
./moses/src/WordLattice.o \
./moses/src/WordsBitmap.o \
./moses/src/WordsRange.o \
./moses/src/XmlOption.o \
./moses/src/hash.o 

CPP_DEPS += \
./moses/src/AlignmentInfo.d \
./moses/src/AlignmentInfoCollection.d \
./moses/src/BilingualDynSuffixArray.d \
./moses/src/BitmapContainer.d \
./moses/src/ChartCell.d \
./moses/src/ChartCellCollection.d \
./moses/src/ChartHypothesis.d \
./moses/src/ChartHypothesisCollection.d \
./moses/src/ChartManager.d \
./moses/src/ChartTranslationOption.d \
./moses/src/ChartTranslationOptionCollection.d \
./moses/src/ChartTranslationOptionList.d \
./moses/src/ChartTrellisDetour.d \
./moses/src/ChartTrellisDetourQueue.d \
./moses/src/ChartTrellisNode.d \
./moses/src/ChartTrellisPath.d \
./moses/src/ConfusionNet.d \
./moses/src/DecodeFeature.d \
./moses/src/DecodeGraph.d \
./moses/src/DecodeStep.d \
./moses/src/DecodeStepGeneration.d \
./moses/src/DecodeStepTranslation.d \
./moses/src/Dictionary.d \
./moses/src/DummyScoreProducers.d \
./moses/src/DynSuffixArray.d \
./moses/src/FFState.d \
./moses/src/Factor.d \
./moses/src/FactorCollection.d \
./moses/src/FactorTypeSet.d \
./moses/src/FeatureFunction.d \
./moses/src/File.d \
./moses/src/FloydWarshall.d \
./moses/src/GenerationDictionary.d \
./moses/src/GlobalLexicalModel.d \
./moses/src/Hypothesis.d \
./moses/src/HypothesisStack.d \
./moses/src/HypothesisStackCubePruning.d \
./moses/src/HypothesisStackNormal.d \
./moses/src/InputFileStream.d \
./moses/src/InputType.d \
./moses/src/LMList.d \
./moses/src/LVoc.d \
./moses/src/LexicalReordering.d \
./moses/src/LexicalReorderingState.d \
./moses/src/LexicalReorderingTable.d \
./moses/src/Manager.d \
./moses/src/NonTerminal.d \
./moses/src/PCNTools.d \
./moses/src/Parameter.d \
./moses/src/PartialTranslOptColl.d \
./moses/src/Phrase.d \
./moses/src/PhraseDictionary.d \
./moses/src/PhraseDictionaryDynSuffixArray.d \
./moses/src/PhraseDictionaryMemory.d \
./moses/src/PhraseDictionaryNode.d \
./moses/src/PhraseDictionaryTree.d \
./moses/src/PhraseDictionaryTreeAdaptor.d \
./moses/src/PrefixTreeMap.d \
./moses/src/ReorderingConstraint.d \
./moses/src/ReorderingStack.d \
./moses/src/RuleCube.d \
./moses/src/RuleCubeItem.d \
./moses/src/RuleCubeQueue.d \
./moses/src/ScoreComponentCollection.d \
./moses/src/ScoreIndexManager.d \
./moses/src/ScoreProducer.d \
./moses/src/Search.d \
./moses/src/SearchCubePruning.d \
./moses/src/SearchNormal.d \
./moses/src/Sentence.d \
./moses/src/SentenceStats.d \
./moses/src/SquareMatrix.d \
./moses/src/StaticData.d \
./moses/src/SyntacticLanguageModel.d \
./moses/src/TargetPhrase.d \
./moses/src/TargetPhraseCollection.d \
./moses/src/ThreadPool.d \
./moses/src/Timer.d \
./moses/src/TranslationOption.d \
./moses/src/TranslationOptionCollection.d \
./moses/src/TranslationOptionCollectionConfusionNet.d \
./moses/src/TranslationOptionCollectionText.d \
./moses/src/TranslationOptionList.d \
./moses/src/TranslationSystem.d \
./moses/src/TreeInput.d \
./moses/src/TrellisPath.d \
./moses/src/TrellisPathCollection.d \
./moses/src/UserMessage.d \
./moses/src/Util.d \
./moses/src/Word.d \
./moses/src/WordLattice.d \
./moses/src/WordsBitmap.d \
./moses/src/WordsRange.d \
./moses/src/XmlOption.d \
./moses/src/hash.d 


# Each subdirectory must supply rules for building sources it contributes
moses/src/%.o: ../moses/src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


